WITH MAX_COUNT AS(
    SELECT R.MEMBER_ID, COUNT(R.REVIEW_ID) AS REVIEW_COUNT,
    DENSE_RANK() OVER(ORDER BY COUNT(R.REVIEW_ID) DESC) AS DR
    FROM REST_REVIEW R
    GROUP BY R.MEMBER_ID
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MAX_COUNT M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
WHERE M.DR = 1
ORDER BY 3, 2