-- 코드를 작성해주세요
WITH P AS(
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SOC
    FROM ECOLI_DATA
)

SELECT ID,
CASE 
WHEN SOC <= 0.25 THEN 'CRITICAL'
WHEN SOC <= 0.50 THEN 'HIGH'
WHEN SOC <= 0.75 THEN 'MEDIUM'
ELSE 'LOW' END AS COLONY_NAME
FROM P
ORDER BY ID
