WITH CART_MILK AS(
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Milk"
),
CART_YOGURT AS(
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Yogurt"
)

SELECT DISTINCT CM.CART_ID
FROM CART_MILK CM JOIN CART_YOGURT CY
ON CM.CART_ID = CY.CART_ID
ORDER BY 1