-- 코드를 입력하세요

WITH C AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) > 4
)

SELECT MONTH(START_DATE) AS MONTH, CR.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR
WHERE CR.CAR_ID IN (SELECT CAR_ID FROM C) AND START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS > 0
ORDER BY 1, 2 DESC