WITH MAX_VALUE AS(
    SELECT CATEGORY, MAX(PRICE) AS MP
    FROM FOOD_PRODUCT
    GROUP BY 1
)

SELECT FP.CATEGORY, MV.MP AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP, MAX_VALUE MV
WHERE FP.CATEGORY = MV.CATEGORY
AND FP.PRICE = MV.MP
AND FP.CATEGORY IN ("과자", "국", "김치", "식용유")
ORDER BY 2 DESC